### Nominal Encoding/OpenHotEncoding:
In this encoding technique we encode the category of the categorical variable into numeric values 0's and 1's , but there is issue with such type of encoding is that ,if  a categorical variable contains 100 unique categories then after performing OneHotEncoding it will add 100 new features into the dataset which creates 'SparseMatrix' because of this sparse matrix my machine learning model will got the issue of 'OVERFITTING' means it will learn each and every pattern of the trained dataset and it will not perform well on new data.

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
##create a Dataframe
df=pd.DataFrame({
    'color':['red','blue','green']
})

In [3]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['color']]).toarray()

In [4]:
df_encoded=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [5]:
encoder.transform([['red']]).toarray()

/Users/ashish/code/ENV/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1.]])

In [6]:
df_encoded

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0

In [7]:
pd.concat([df,df_encoded],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0