#### TARGET GUIDED ORDINAL ENCODING
In this technique we encode the categorical variable based on it's relationship with Target Variable. This encoding technique is very useful when categorical variable contains large number of unique values and we want to use this categorical variable as feature in my machine learning model.

in this encoding technique we replace each category of the categorical variable into numeric value based on the mean or median of the target varibale with respect to that particular category.This creates the Monotonic realtionship between Categorical Variable and Target Variable which somehow improves the Predictive Power of my machine learning Model.

In [1]:
import pandas as pd

In [2]:
import pandas as pd
##create a sample DataFrame with a categorical Variable and a target variable
df=pd.DataFrame(
    {
        'city':['New York','London','Paris','Tokyo','New York','Paris'],
        'price':[200,150,300,250,180,320]
    }
)

In [3]:
df.head()

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180

In [4]:
mean_value=df.groupby('city')['price'].mean().to_dict()

In [5]:
mean_value

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [6]:
df['target_encode']=df['city'].map(mean_value)

In [7]:
df.head()

       city  price  target_encode
0  New York    200          190.0
1    London    150          150.0
2     Paris    300          310.0
3     Tokyo    250          250.0
4  New York    180          190.0

In [8]:
df[['target_encode','price']]

   target_encode  price
0          190.0    200
1          150.0    150
2          310.0    300
3          250.0    250
4          190.0    180
5          310.0    320